# Generated by Django 4.2.24 on 2026-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
