# Generated by Django 4.2.24 on 2026-08-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='salary',
        ),
    ]
