# Generated by Django 4.2.24 on 2026-08-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
    ]
